type Pelicula {
    id: ID!
    titulo: String!
    duracionMinutos: Int!
    recaudacionTaquilla: Float!
    esSaga: Boolean!
}

type Query {
    listarPeliculas: [Pelicula]!
    buscarPeliculaPorId(id: ID!): Pelicula
}

type Mutation {
    crearPelicula(peliculaInput: PeliculaInput!): Pelicula
    actualizarPelicula(id: ID!, peliculaInput: PeliculaInput!): Pelicula
    eliminarPelicula(id: ID!): Boolean!
}

input PeliculaInput {
    id: ID!
    titulo: String!
    duracionMinutos: Int!
    recaudacionTaquilla: Float!
    esSaga: Boolean!
}