type Pelicula {
    id: ID!
    titulo: String!
    duracionMinutos: Int!
    recaudacionTaquilla: Float!
    esSaga: Boolean!
    fechaEstreno: String!
}

input PeliculaInput {
    id: ID!
    titulo: String!
    duracionMinutos: Int!
    recaudacionTaquilla: Float!
    esSaga: Boolean!
    fechaEstreno: String!
}

type Query {
    listarPeliculas(esSaga: Boolean, titulo: String): [Pelicula]
    buscarPeliculaPorId(id: ID!): Pelicula
}

type Mutation {
    crearPelicula(peliculaInput: PeliculaInput!): Pelicula
    actualizarPelicula(id: ID!, peliculaInput: PeliculaInput!): Pelicula
    eliminarPelicula(id: ID!): Boolean
}